version: "3.8"
services: 
  springboot-app:
    #container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: " "
      MYSQL_PORT: 3306
      
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: springbootdb
      MYSQL_ALLOW_EMPTY_PASSWORD: " "
